### PR TITLE
#6 add wordpress_interop.serializer config (with CamelCaseToSnakeCaseNameConverter)

### PR DESCRIPTION
**Pull request by novotnicek**

### CODE REVIEW

**Comment by williarin** [comment]
Hi Peter, thanks for your PR and your interest in those projects!
I'll look at it this week and check if that works well with an existing code base. The problem I see that might happen is that in this case the normalizers included by Symfony are not used in this one. For example to initialize the base serializer without Symfony, I would use this:

```php
$objectNormalizer = new ObjectNormalizer(
    new ClassMetadataFactory(new AnnotationLoader(new AnnotationReader())),
    new CamelCaseToSnakeCaseNameConverter(),
    null,
    new ReflectionExtractor()
);

$serializer = new Serializer([
    new DateTimeNormalizer(),
    new ArrayDenormalizer(),
    new SerializedArrayDenormalizer($objectNormalizer),
    $objectNormalizer,
]);

$manager = new EntityManager($connection, $serializer);
```

Maybe we should use a compiler pass to add this `CamelCaseToSnakeCaseNameConverter` to the existing Symfony serializer so we avoid duplicated serializers and it's simpler to extend from the main app. Would you agree?

**Comment by novotnicek** [comment]
Yes, sorry for the late reply (i had some work).

Your solutions seems right, but i don't know how make CompilerPass with this functionality...

I have second solution, maybe isn't so good, but enough for my needs.

I commited it into current PR. Please, can you check it, if is enough for mainstream?

My idea(/concept) is wordpress-interop-bundle used (without rewriting my default serializer settings) like:
```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Williarin\WordpressInterop\Bridge\Entity\Post;
use Williarin\WordpressInterop\EntityManagerInterface;

class WpPostController extends AbstractController
{
    public function __construct(
        private EntityManagerInterface $wp,
    ) {}

    public function getPost(int $postId): Response
    {
        try {
            $post = $this->wp->getRepository(Page::class)->find($postId);
        } catch (\Throwable $th) {
            throw $this->createNotFoundException();
        }

        return $this->render('wp_post/index.html.twig', [
            'post' => $post,
        ]);
    }
}
```

**Comment by novotnicek** [comment]
Hi William, can you check/squash/merge this changes? Or have some suggestions?

I have multisite WP, and changes in this branch simplify my codebase.

I can define more entity_managers (`./config/packages/williarin_wordpress_interop.yaml`):
```yaml
williarin_wordpress_interop:
    entity_managers:
        default:
            connection: default
            tables_prefix: 'wp_'
        secondSite:
            connection: default
            tables_prefix: 'wp_2_'
```
and then simply call ManagerRegistry (and serializer, etc. will be configured by library), example:
```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Williarin\WordpressInterop\Bridge\Entity\Page;
use Williarin\WordpressInteropBundle\Bridge\ManagerRegistry;

class WpPostController extends AbstractController
{
    public function __construct(
        private ManagerRegistry $wp,
    ) {}

    #[Route('/{path<.*>}', name: 'wp_path', priority: -100)]
    public function rescuePath(string $path): Response
    {
        $aPath = explode('/', $path);

        if (empty(end($aPath))) {
            array_pop($aPath);
        }

        try {
            $post = $this->wp->getRepository(Page::class, 'secondSite')->findOneBy([
                'post_name' => end($aPath),
                'post_status' => 'publish',
            ]);
        } catch (\Throwable $th) {
            throw $this->createNotFoundException();
        }

        return $this->render('wp_post/index.html.twig', [
            'post' => $post,
        ]);
    }
}
```
IMHO this solution is better like configuring ObjectNormalizer and Serializer in higher level of application. If you see some problem, can you comment please?

Thanks.

**Comment by williarin** [comment]
Hi Peter, can you try #8 with your project and let me know if it solves your problem?

**Comment by novotnicek** [comment]
Yes, everything work fine for me. Thank you very much.

#8 solves the problem nicely. I closing this.

**Pull request closed without merging**
